const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#planCanvas'),ctx=canvas.getContext('2d'),svg=$('#overlay'),sheet=$('#sheet'),empty=$('#emptyState');
const splitCanvas=$('#splitCanvas'),splitCtx=splitCanvas.getContext('2d'),splitSheet=$('#splitSheet');
const state={tool:'select',pdf:null,page:1,pages:1,file:'',zoom:1,scale:null,calPts:[],draft:[],drawing:false,items:[],strokes:[],image:null,dxf:null,cadPoints:[],multiId:null,docs:[],activeDoc:-1,snap:true,snapMarker:null,selected:null,dragRef:null,justDragged:0,group:'General',split:false,splitPage:2,tradePack:localStorage.getItem('atlasTradePack')||'railing',projectId:null,projectName:''};
const colors={length:'#4a9eff',multilength:'#9b7cff',area:'#42d392',angle:'#ff73df',joint:'#ff8b3d',count:'#e2ac3e',pen:'#ff5d68',calibrate:'#e2ac3e'};
let pdfjs=null;
try{pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs'}catch(e){console.warn('PDF support unavailable',e)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setTool(tool){if(state.tool==='multilength'&&tool!=='multilength')state.multiId=null;state.tool=tool;state.draft=[];state.snapMarker=null;state.selected=tool==='select'?state.selected:null;$$('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));svg.classList.toggle('pan',tool==='pan');const hints={select:'Click a measurement, then drag its gold handles to edit it. Delete removes the selected item.',pan:'Drag the plan area to pan.',calibrate:'Click two points with a known distance.',length:'Click each connected point. Double-click or press Enter to finish.',multilength:'Click start and end for each separate segment. Press Enter when complete.',area:'Click each corner. Double-click or press Enter to close.',angle:'Click the first leg, corner, and second leg.',joint:'Click along the expansion joint. Double-click or press Enter to finish.',count:'Click each item to add a count.',pen:'Drag to draw a freehand markup.'};$('#hint').textContent=hints[tool];renderOverlay()}
$$('.tool[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function captureDoc(){if(state.activeDoc<0||!state.docs[state.activeDoc])return;Object.assign(state.docs[state.activeDoc],{page:state.page,zoom:state.zoom,scale:state.scale,items:state.items,strokes:state.strokes,multiId:state.multiId,group:state.group,split:state.split,splitPage:state.splitPage,cadPoints:state.cadPoints})}
async function activateDoc(index){captureDoc();const d=state.docs[index];if(!d)return;state.activeDoc=index;Object.assign(state,{file:d.file,pdf:d.pdf,image:d.image,dxf:d.dxf||null,cadPoints:d.cadPoints||[],page:d.page,pages:d.pages,zoom:d.zoom,scale:d.scale,items:d.items,strokes:d.strokes,multiId:d.multiId,group:d.group||'General',split:!!d.split,splitPage:d.splitPage||Math.min(2,d.pages),draft:[],selected:null});applyTradePack(state.tradePack,true);$('#takeoffGroup').value=state.group;$('#docTitle').textContent=d.file;empty.hidden=true;sheet.hidden=false;setupPageControls();if(state.pdf)await renderPage();else if(state.dxf)renderDxf();else renderImage();await updateSplit();refreshUI();renderTabs();fitView();renderPageThumbs()}
function renderTabs(){const bar=$('#docBar');bar.innerHTML=state.docs.map((d,i)=>`<button class="doc-tab ${i===state.activeDoc?'active':''}" data-doc="${i}" title="${esc(d.file)}"><span class="name">${esc(d.file)}</span><span class="close" data-close="${i}" aria-label="Close ${esc(d.file)}">×</span></button>`).join('');$$('[data-doc]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-close]'))return;activateDoc(Number(b.dataset.doc))});$$('[data-close]').forEach(b=>b.onclick=e=>{e.stopPropagation();closeDoc(Number(b.dataset.close))})}
async function closeDoc(index){captureDoc();const removed=state.docs[index];if(removed?.objectUrl)URL.revokeObjectURL(removed.objectUrl);state.docs.splice(index,1);state.activeDoc=-1;if(!state.docs.length){Object.assign(state,{file:'',pdf:null,image:null,dxf:null,cadPoints:[],items:[],split:false});sheet.hidden=true;splitSheet.hidden=true;empty.hidden=false;$('#docTitle').textContent='No plan open';$('#pageSection').hidden=true;renderTabs();refreshUI();return}await activateDoc(Math.min(index,state.docs.length-1))}
async function openFile(file){if(!file)return;const url=URL.createObjectURL(file);try{let pdf=null,image=null,dxf=null,pages=1,scale=null;if(file.name.toLowerCase().endsWith('.dxf')){dxf=parseDxf(await file.text());if(!dxf.entities.length)throw new Error('No supported DXF linework was found')}else if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){if(!pdfjs)throw new Error('PDF viewer could not load');pdf=await pdfjs.getDocument(url).promise;pages=pdf.numPages}else image=await loadImage(url);const d={file:file.name,mime:file.type||'',source:file,objectUrl:url,pdf,image,dxf,cadPoints:[],page:1,pages,zoom:1,scale,items:[],strokes:[],multiId:null,group:'General',split:false,splitPage:Math.min(2,pages)};state.docs.push(d);await activateDoc(state.docs.length-1);setTool(dxf?'length':'calibrate');if(dxf&&state.scale)toast('DXF opened with drawing-unit scale')}catch(e){URL.revokeObjectURL(url);toast(e.message||'Could not open this plan')}}
function loadImage(url){return new Promise((res,rej)=>{const i=new Image;i.onload=()=>res(i);i.onerror=rej;i.src=url})}
function parseDxf(text){const lines=text.replace(/\r/g,'').split('\n'),pairs=[];for(let i=0;i+1<lines.length;i+=2)pairs.push({code:Number(lines[i].trim()),value:lines[i+1].trim()});let units=0;for(let i=0;i<pairs.length-1;i++)if(pairs[i].code===9&&pairs[i].value==='$INSUNITS')units=Number(pairs[i+1].value)||0;const entities=[];for(let i=0;i<pairs.length;i++){if(pairs[i].code!==0||!['LINE','LWPOLYLINE','ARC','CIRCLE'].includes(pairs[i].value))continue;const type=pairs[i].value,data=[];for(i=i+1;i<pairs.length&&pairs[i].code!==0;i++)data.push(pairs[i]);i--;const one=c=>Number(data.find(p=>p.code===c)?.value||0);if(type==='LINE')entities.push({type,points:[{x:one(10),y:one(20)},{x:one(11),y:one(21)}]});if(type==='LWPOLYLINE'){const points=[];for(let n=0;n<data.length;n++)if(data[n].code===10){const y=data.slice(n+1).find(p=>p.code===20);points.push({x:Number(data[n].value),y:Number(y?.value||0)})}if(points.length>1)entities.push({type,points,closed:!!(one(70)&1)})}if(type==='ARC'||type==='CIRCLE'){const cx=one(10),cy=one(20),r=one(40),start=type==='CIRCLE'?0:one(50),end=type==='CIRCLE'?360:one(51),span=((end-start)+360)%360||360,points=[];for(let n=0;n<=Math.max(12,Math.ceil(span/8));n++){const a=(start+span*n/Math.max(12,Math.ceil(span/8)))*Math.PI/180;points.push({x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)})}entities.push({type,points,closed:type==='CIRCLE'})}}return{entities,units}}
function renderDxf(){const all=state.dxf.entities.flatMap(e=>e.points),xs=all.map(p=>p.x),ys=all.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),dx=Math.max(1,maxX-minX),dy=Math.max(1,maxY-minY),max=1800,s=Math.min((max-80)/dx,(1200-80)/dy);canvas.width=Math.round(dx*s+80);canvas.height=Math.round(dy*s+80);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#16202d';ctx.lineWidth=1.2;state.cadPoints=[];state.dxf.screenEntities=state.dxf.entities.map(e=>({...e,points:e.points.map(p=>({x:40+(p.x-minX)*s,y:40+(maxY-p.y)*s}))}));for(const e of state.dxf.screenEntities){ctx.beginPath();e.points.forEach((p,i)=>{i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);state.cadPoints.push(p)});if(e.closed)ctx.closePath();ctx.stroke()}const unitFt={1:1/12,2:1,4:0.00328084,5:0.0328084,6:3.28084}[state.dxf.units];if(unitFt&&!state.scale)state.scale=unitFt/s;sizeSheet();renderOverlay()}
async function renderPage(){const page=await state.pdf.getPage(state.page),base=page.getViewport({scale:1.5});canvas.width=Math.round(base.width);canvas.height=Math.round(base.height);await page.render({canvasContext:ctx,viewport:base}).promise;sizeSheet();renderOverlay()}
function renderImage(){const i=state.image,max=2200,s=Math.min(1,max/Math.max(i.width,i.height));canvas.width=Math.round(i.width*s);canvas.height=Math.round(i.height*s);ctx.drawImage(i,0,0,canvas.width,canvas.height);sizeSheet();renderOverlay()}
function sizeSheet(){sheet.style.width=canvas.width*state.zoom+'px';sheet.style.height=canvas.height*state.zoom+'px';canvas.style.width='100%';canvas.style.height='100%';svg.setAttribute('viewBox',`0 0 ${canvas.width} ${canvas.height}`);if(!splitSheet.hidden){splitSheet.style.width=splitCanvas.width*state.zoom+'px';splitSheet.style.height=splitCanvas.height*state.zoom+'px';splitCanvas.style.width='100%';splitCanvas.style.height='100%'}}
function setupPageControls(){const sel=$('#splitPage');sel.innerHTML=Array.from({length:state.pages},(_,i)=>`<option value="${i+1}">Page ${i+1}</option>`).join('');state.splitPage=Math.max(1,Math.min(state.pages,state.splitPage));sel.value=state.splitPage;$('#splitBtn').disabled=!state.pdf||state.pages<2;$('#pageSection').hidden=!state.pdf||state.pages<2}
async function updateSplit(){state.split=!!(state.split&&state.pdf&&state.pages>1);$('#stageGrid').classList.toggle('split',state.split);splitSheet.hidden=!state.split;$('#splitControls').hidden=!state.split;$('#splitBtn').textContent=state.split?'Close split':'Split view';if(!state.split)return;const p=await state.pdf.getPage(state.splitPage),view=p.getViewport({scale:1.5});splitCanvas.width=Math.round(view.width);splitCanvas.height=Math.round(view.height);await p.render({canvasContext:splitCtx,viewport:view}).promise;$('#splitBadge').textContent=`Compare page ${state.splitPage}`;sizeSheet()}
async function renderPageThumbs(){const wrap=$('#pageThumbs');wrap.innerHTML='';if(!state.pdf||state.pages<2)return;const docIndex=state.activeDoc;for(let n=1;n<=state.pages;n++){if(docIndex!==state.activeDoc)return;const b=document.createElement('button');b.className='thumb'+(n===state.page?' active':'');b.dataset.page=n;b.innerHTML=`<canvas></canvas><strong>Page ${n}</strong>`;b.onclick=()=>goToPage(n);wrap.appendChild(b);try{const page=await state.pdf.getPage(n),raw=page.getViewport({scale:1}),scale=Math.min(62/raw.width,80/raw.height),view=page.getViewport({scale});const c=b.querySelector('canvas');c.width=Math.max(1,Math.round(view.width));c.height=Math.max(1,Math.round(view.height));await page.render({canvasContext:c.getContext('2d'),viewport:view}).promise}catch(e){b.querySelector('canvas').remove()}}}
function highlightThumbs(){$$('.thumb').forEach(b=>b.classList.toggle('active',Number(b.dataset.page)===state.page))}
function pageItems(){return state.items.filter(i=>i.page===state.page)}
function rawPt(ev){const r=svg.getBoundingClientRect();return{x:(ev.clientX-r.left)*canvas.width/r.width,y:(ev.clientY-r.top)*canvas.height/r.height}}
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function pathD(points,close=false){return points.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')+(close?' Z':'')}
function vertexRefs(){const out=[];for(const it of pageItems()){if(it.type==='multilength')it.segments.forEach((seg,si)=>seg.forEach((p,pi)=>out.push({item:it,segment:si,point:pi,p})));else it.points.forEach((p,pi)=>out.push({item:it,segment:null,point:pi,p}))}return out}
function sameRef(a,b){return a&&b&&a.item.id===b.item.id&&a.segment===b.segment&&a.point===b.point}
function snapPoint(p,exclude=null){if(!state.snap)return{point:p,snapped:false};const limit=14/state.zoom;let best=null,bestD=limit;for(const r of vertexRefs()){if(sameRef(r,exclude))continue;const d=dist(p,r.p);if(d<bestD){best=r.p;bestD=d}}for(const cp of state.cadPoints||[]){const d=dist(p,cp);if(d<bestD){best=cp;bestD=d}}if(best)return{point:{x:best.x,y:best.y},snapped:true,kind:'point'};const anchor=state.draft.at(-1);if(anchor){if(Math.abs(p.x-anchor.x)<limit)return{point:{x:anchor.x,y:p.y},snapped:true,kind:'vertical'};if(Math.abs(p.y-anchor.y)<limit)return{point:{x:p.x,y:anchor.y},snapped:true,kind:'horizontal'}}return{point:p,snapped:false}}
function nearestVertex(p){let best=null,bestD=16/state.zoom;for(const r of vertexRefs()){const d=dist(p,r.p);if(d<bestD){best=r;bestD=d}}return best}
function pointSegDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return dist(p,a);let t=((p.x-a.x)*dx+(p.y-a.y)*dy)/l;t=Math.max(0,Math.min(1,t));return dist(p,{x:a.x+t*dx,y:a.y+t*dy})}
function itemSegments(it){if(it.type==='count')return[];if(it.type==='multilength')return it.segments;const ps=it.points,segs=[];for(let i=1;i<ps.length;i++)segs.push([ps[i-1],ps[i]]);if(it.type==='area'&&ps.length>2)segs.push([ps.at(-1),ps[0]]);return segs}
function hitItem(p){const v=nearestVertex(p);if(v)return v.item;let best=null,d0=12/state.zoom;for(const it of pageItems()){if(it.type==='count'){const d=dist(p,it.points[0]);if(d<d0){best=it;d0=d}}for(const seg of itemSegments(it)){const d=pointSegDistance(p,...seg);if(d<d0){best=it;d0=d}}}return best}
function getRefPoint(r){return r.segment==null?r.item.points[r.point]:r.item.segments[r.segment][r.point]}
function setRefPoint(r,p){const dest=getRefPoint(r);dest.x=p.x;dest.y=p.y;delete r.item.railLayout}
function renderOverlay(){svg.innerHTML='';const add=(tag,attrs)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);svg.appendChild(n);return n};for(const it of pageItems())drawItem(it,add);for(const st of state.strokes.filter(s=>s.page===state.page))add('path',{d:pathD(st.points),fill:'none',stroke:colors.pen,'stroke-width':3,'stroke-linecap':'round','stroke-linejoin':'round','vector-effect':'non-scaling-stroke'});if(state.draft.length){const c=colors[state.tool]||colors.length;if(state.tool!=='count')add('path',{d:pathD(state.draft),fill:state.tool==='area'?c+'22':'none',stroke:c,'stroke-width':2,'stroke-dasharray':'7 5','vector-effect':'non-scaling-stroke'});state.draft.forEach(p=>add('circle',{cx:p.x,cy:p.y,r:5,fill:c,stroke:'#fff','stroke-width':1,'vector-effect':'non-scaling-stroke'}))}if(state.selected){for(const r of vertexRefs().filter(r=>r.item.id===state.selected)){const p=getRefPoint(r);add('circle',{cx:p.x,cy:p.y,r:7,fill:'#e2ac3e',stroke:'#16120a','stroke-width':2,'vector-effect':'non-scaling-stroke'})}}if(state.snapMarker){const p=state.snapMarker;add('circle',{cx:p.x,cy:p.y,r:10,fill:'none',stroke:'#e2ac3e','stroke-width':2,'vector-effect':'non-scaling-stroke'});add('path',{d:`M${p.x-14} ${p.y}H${p.x+14}M${p.x} ${p.y-14}V${p.y+14}`,stroke:'#e2ac3e','stroke-width':1,'vector-effect':'non-scaling-stroke'})}}
function drawItem(it,add){
  const c=colors[it.type]||colors.length;
  if(it.type==='count'){
    add('circle',{cx:it.points[0].x,cy:it.points[0].y,r:10,fill:c,stroke:'#17120a','stroke-width':2,'vector-effect':'non-scaling-stroke'});
    const t=add('text',{x:it.points[0].x,y:it.points[0].y+4,'text-anchor':'middle',fill:'#17120a','font-size':11,'font-weight':800});t.textContent=it.seq;
  }else if(it.type==='multilength'){
    it.segments.forEach((seg,n)=>{add('path',{d:pathD(seg),fill:'none',stroke:c,'stroke-width':state.selected===it.id?5:3,'vector-effect':'non-scaling-stroke'});const p=seg[1],t=add('text',{x:p.x+8,y:p.y-8,fill:c,'font-size':12,'font-weight':800,stroke:'#fff','stroke-width':3,'paint-order':'stroke'});t.textContent=(n+1)+': '+feet(dist(seg[0],seg[1])).toFixed(2)+' LF'});
  }else{
    add('path',{d:pathD(it.points,it.type==='area'),fill:it.type==='area'?c+'25':'none',stroke:c,'stroke-width':state.selected===it.id?5:3,'stroke-dasharray':it.type==='joint'?'10 7':'','vector-effect':'non-scaling-stroke','stroke-linejoin':'round'});
    const p=it.type==='angle'?it.points[1]:it.points[Math.floor(it.points.length/2)],t=add('text',{x:p.x+8,y:p.y-8,fill:c,'font-size':13,'font-weight':800,stroke:'#fff','stroke-width':3,'paint-order':'stroke'});
    t.textContent=formatValue(it);
    if(it.railLayout?.notation){
      const layout=add('text',{x:p.x+8,y:p.y+10,fill:'#8a5a00','font-size':12,'font-weight':800,stroke:'#fff','stroke-width':3,'paint-order':'stroke'});
      layout.textContent=it.railLayout.notation;
    }
  }
}
function feet(px){return state.scale?px*state.scale:0}
function polyLength(ps){return ps.slice(1).reduce((s,p,i)=>s+dist(ps[i],p),0)}
function polyArea(ps){let a=0;for(let i=0,j=ps.length-1;i<ps.length;j=i++)a+=(ps[j].x+ps[i].x)*(ps[j].y-ps[i].y);return Math.abs(a/2)}
function linearValue(it){return it.type==='multilength'?it.segments.reduce((s,seg)=>s+feet(dist(seg[0],seg[1])),0):feet(polyLength(it.points))}
function angleValue(ps){if(ps.length<3)return 0;const a=Math.atan2(ps[0].y-ps[1].y,ps[0].x-ps[1].x),b=Math.atan2(ps[2].y-ps[1].y,ps[2].x-ps[1].x);let d=Math.abs((b-a)*180/Math.PI);return d>180?360-d:d}
function segmentAngle(seg){let a=Math.atan2(-(seg[1].y-seg[0].y),seg[1].x-seg[0].x)*180/Math.PI;if(a<0)a+=360;return a}
function formatValue(it){if(['length','multilength'].includes(it.type))return linearValue(it).toFixed(2)+' LF';if(it.type==='joint')return`EJ-${it.seq||1} · ${linearValue(it).toFixed(2)} LF`;if(it.type==='area')return(state.scale?polyArea(it.points)*state.scale*state.scale:0).toFixed(2)+' SF';if(it.type==='angle')return angleValue(it.points).toFixed(1)+'°';return'Count '+it.seq}
function newItem(data){return{id:crypto.randomUUID(),group:state.group,...data}}
svg.addEventListener('click',ev=>{if(sheet.hidden||state.tool==='pan'||state.tool==='pen')return;const raw=rawPt(ev);if(state.tool==='select'){if(performance.now()-state.justDragged<250)return;const it=hitItem(raw);state.selected=it?.id||null;refreshUI();return}const snap=snapPoint(raw),p=snap.point;state.snapMarker=snap.snapped?p:null;if(state.tool==='count'){const seq=pageItems().filter(i=>i.type==='count').length+1;state.items.push(newItem({type:'count',page:state.page,points:[p],seq}));refreshUI();return}state.draft.push(p);if(state.tool==='angle'&&state.draft.length===3){finishShape('angle');return}if(state.tool==='multilength'&&state.draft.length===2){let group=state.items.find(i=>i.id===state.multiId);if(!group){group=newItem({type:'multilength',page:state.page,segments:[]});state.items.push(group);state.multiId=group.id}group.segments.push([...state.draft]);state.draft=[];refreshUI();toast('Segment added — '+group.segments.length+' total');return}if(state.tool==='calibrate'&&state.draft.length===2){state.calPts=[...state.draft];$('#scaleModal').classList.add('show');$('#knownValue').focus()}renderOverlay()});
svg.addEventListener('dblclick',ev=>{ev.preventDefault();if(state.tool==='length'&&state.draft.length>=2)finishShape('length');if(state.tool==='area'&&state.draft.length>=3)finishShape('area');if(state.tool==='joint'&&state.draft.length>=2)finishShape('joint')});
function finishShape(type){state.items.push(newItem({type,page:state.page,points:[...state.draft],seq:type==='joint'?state.items.filter(i=>i.type==='joint').length+1:undefined}));state.draft=[];refreshUI();toast(type==='area'?'Area added':type==='angle'?'Angle added':type==='joint'?'Expansion joint added':'Length added')}
svg.addEventListener('pointerdown',ev=>{if(state.tool==='select'){const ref=nearestVertex(rawPt(ev));if(ref){state.dragRef=ref;state.selected=ref.item.id;state.drawing=true;svg.setPointerCapture(ev.pointerId);renderOverlay()}return}if(state.tool==='pen'){state.drawing=true;state.draft=[rawPt(ev)];svg.setPointerCapture(ev.pointerId)}if(state.tool==='pan'){state.drawing=true;state.pan={x:ev.clientX,y:ev.clientY,l:$('#stageWrap').scrollLeft,t:$('#stageWrap').scrollTop};svg.setPointerCapture(ev.pointerId)}});
svg.addEventListener('pointermove',ev=>{const raw=rawPt(ev);let cursor=raw;if(state.tool==='select'&&state.drawing&&state.dragRef){const snap=snapPoint(raw,state.dragRef);cursor=snap.point;setRefPoint(state.dragRef,cursor);state.snapMarker=snap.snapped?cursor:null;renderOverlay()}else if(!['select','pan','pen'].includes(state.tool)){const snap=snapPoint(raw);cursor=snap.point;state.snapMarker=snap.snapped?cursor:null;renderOverlay()}$('#coords').innerHTML=`x ${Math.round(cursor.x)} &nbsp; y ${Math.round(cursor.y)}`;if(state.tool==='pen'&&state.drawing){state.draft.push(raw);renderOverlay()}if(state.tool==='pan'&&state.drawing){$('#stageWrap').scrollLeft=state.pan.l-(ev.clientX-state.pan.x);$('#stageWrap').scrollTop=state.pan.t-(ev.clientY-state.pan.y)}});
svg.addEventListener('pointerleave',()=>{if(!state.drawing){state.snapMarker=null;renderOverlay()}});
svg.addEventListener('pointerup',()=>{if(state.tool==='pen'&&state.drawing&&state.draft.length>1){state.strokes.push({page:state.page,points:[...state.draft]});state.draft=[]}if(state.tool==='select'&&state.dragRef){state.justDragged=performance.now();state.dragRef=null}state.drawing=false;state.snapMarker=null;refreshUI()});
$('#saveScale').onclick=()=>{const val=Number($('#knownValue').value),unit=$('#knownUnit').value;if(!val||!state.calPts.length)return;const ft=unit==='ft'?val:unit==='in'?val/12:val*3.28084;state.scale=ft/dist(state.calPts[0],state.calPts[1]);state.draft=[];$('#scaleModal').classList.remove('show');refreshUI();setTool('length');toast('Scale calibrated')};
$('#cancelScale').onclick=()=>{$('#scaleModal').classList.remove('show');state.draft=[];renderOverlay()};
function itemName(it){return{length:'Continuous length',multilength:'Multi-segment takeoff',area:'Area takeoff',angle:'Angle measurement',joint:'Expansion joint',count:'Count item'}[it.type]||it.type}
function refreshUI(){$('#pageLabel').textContent=state.file?`${state.page} / ${state.pages}`:'— / —';$('#prevPage').disabled=state.page<=1;$('#nextPage').disabled=state.page>=state.pages;$('#scaleText').textContent=state.scale?`1 in = ${(state.scale*72).toFixed(2)} ft`:'Not calibrated';$('#scalePill').textContent=state.scale?'Calibrated':'Required';$('#scalePill').classList.toggle('ready',!!state.scale);$('#zoomLabel').textContent=Math.round(state.zoom*100)+'%';$('#measurementCount').textContent=state.items.length;$('#snapToggle').checked=state.snap;const list=$('#measureList');if(!state.items.length)list.innerHTML='<div class="no-items">Your takeoff items will appear here.</div>';else list.innerHTML=state.items.map((it,i)=>`<div class="item ${state.selected===it.id?'selected':''}" data-select="${it.id}"><span class="swatch" style="background:${colors[it.type]||colors.length}"></span><div><b>${itemName(it)}</b><small>${esc(it.group||'General')} · Page ${it.page} · ${it.type==='multilength'?it.segments.length+' segments':'Item '+(i+1)}${it.type==='length'&&it.points.length>1?' · '+segmentAngle([it.points[0],it.points[1]]).toFixed(1)+'°':''}</small></div><div><div class="value">${formatValue(it)}</div><button data-delete="${it.id}" aria-label="Delete item">×</button></div>${it.type==='multilength'?`<div class="segment-list">${it.segments.map((s,n)=>`<div class="segment-row"><span>Section ${n+1}: ${feet(dist(s[0],s[1])).toFixed(2)} LF · ${segmentAngle(s).toFixed(1)}°</span><button data-delete-seg="${it.id}:${n}" aria-label="Delete section ${n+1}">×</button></div>`).join('')}</div>`:''}</div>`).join('');$$('[data-select]').forEach(el=>el.onclick=e=>{if(e.target.closest('button'))return;state.selected=el.dataset.select;setTool('select');refreshUI()});$$('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.items=state.items.filter(i=>i.id!==b.dataset.delete);if(state.multiId===b.dataset.delete)state.multiId=null;if(state.selected===b.dataset.delete)state.selected=null;refreshUI()});$$('[data-delete-seg]').forEach(b=>b.onclick=e=>{e.stopPropagation();const[id,n]=b.dataset.deleteSeg.split(':'),it=state.items.find(i=>i.id===id);if(!it)return;it.segments.splice(Number(n),1);if(!it.segments.length){state.items=state.items.filter(i=>i.id!==id);if(state.multiId===id)state.multiId=null}refreshUI()});$('#totalLength').textContent=state.items.filter(i=>i.type==='length'||i.type==='multilength').reduce((s,i)=>s+linearValue(i),0).toFixed(2)+' LF';$('#totalArea').textContent=state.items.filter(i=>i.type==='area').reduce((s,i)=>s+(state.scale?polyArea(i.points)*state.scale*state.scale:0),0).toFixed(2)+' SF';$('#totalCount').textContent=state.items.filter(i=>i.type==='count').length;highlightThumbs();sizeSheet();renderOverlay()}
async function goToPage(n){if(n<1||n>state.pages||n===state.page)return;state.page=n;state.draft=[];state.selected=null;await renderPage();refreshUI();fitView()}
async function changePage(d){await goToPage(state.page+d)}
$('#prevPage').onclick=()=>changePage(-1);$('#nextPage').onclick=()=>changePage(1);$('#filePicker').onchange=async e=>{for(const file of e.target.files)await openFile(file);e.target.value=''};
function setZoom(z){state.zoom=Math.max(.2,Math.min(4,z));refreshUI()}$('#zoomIn').onclick=()=>setZoom(state.zoom*1.2);$('#zoomOut').onclick=()=>setZoom(state.zoom/1.2);function fitView(){if(sheet.hidden)return;const factor=state.split?2:1,w=($('#stageWrap').clientWidth-90-(state.split?28:0))/factor,h=$('#stageWrap').clientHeight-90;setZoom(Math.min(w/canvas.width,h/canvas.height,1.4))}$('#fitBtn').onclick=fitView;
$('#snapToggle').onchange=e=>{state.snap=e.target.checked;state.snapMarker=null;toast(state.snap?'Smart snap on':'Smart snap off');renderOverlay()};
const tradeRegistry=window.AtlasTradeRegistry;
const tradePacks=Object.fromEntries((tradeRegistry?.list?.()||[]).map(m=>[m.id,{...m,rail:(m.calculators||[]).includes('rail-layout')}]));
if(!tradePacks.railing)tradePacks.railing={id:'railing',name:'Railing & Fence',groups:['General','862 Type 1 Picket','870 Aluminum Two-Rail','880 Steel Two-Rail','822 Bullet Rail','550-002 Type B Fence','550-003 Gate','Removal'],rail:true};
if(!tradePacks.general)tradePacks.general={id:'general',name:'General Takeoff',groups:['General','Existing conditions','Demolition','Concrete','Electrical','Mechanical','Other'],rail:false};
function renderTradePackSelect(){const sel=$('#tradePackSelect'),current=state.tradePack;sel.innerHTML=Object.values(tradePacks).map(pack=>`<option value="${esc(pack.id)}">${esc(pack.name)}</option>`).join('');sel.value=tradePacks[current]?current:'railing'}
function applyTradePack(id,preserveGroup=false){const pack=tradePacks[id]||tradePacks.railing;state.tradePack=tradePacks[id]?id:'railing';localStorage.setItem('atlasTradePack',state.tradePack);renderTradePackSelect();const selected=preserveGroup&&pack.groups.includes(state.group)?state.group:pack.groups[0];$('#takeoffGroup').innerHTML=pack.groups.map(group=>`<option>${esc(group)}</option>`).join('');state.group=selected;$('#takeoffGroup').value=selected;$('#railSection').hidden=!pack.rail;const note=$('#tradePackNote');if(note)note.textContent=pack.athena?.rules?.length?`Athena trade rules loaded · ${pack.name} v${pack.version||'1'}`:'Trade Packs control the takeoff groups and calculation rules for each trade.'}
window.atlasForgeGetAthenaTradeContext=()=>tradeRegistry?.getAthenaContext?.(state.tradePack)||null;
window.atlasForgeGetTradeModule=()=>tradeRegistry?.get?.(state.tradePack)||null;
$('#tradePackSelect').onchange=e=>{applyTradePack(e.target.value);state.multiId=null;toast(tradePacks[state.tradePack].name+' pack active');refreshUI()};
$('#takeoffGroup').onchange=e=>{state.group=e.target.value;state.multiId=null;syncLayoutProfileFromGroup(true);toast('Takeoff group: '+state.group)};
$('#splitBtn').onclick=async()=>{if(!state.pdf||state.pages<2)return toast('Split view needs a multi-page PDF');state.split=!state.split;if(state.split&&state.splitPage===state.page)state.splitPage=state.page===state.pages?1:state.page+1;$('#splitPage').value=state.splitPage;await updateSplit();fitView()};
$('#splitPage').onchange=async e=>{state.splitPage=Number(e.target.value);await updateSplit()};
$('#undoBtn').onclick=()=>{if(state.draft.length)state.draft.pop();else if(state.items.length)state.items.pop();else if(state.strokes.length)state.strokes.pop();refreshUI()};$('#clearBtn').onclick=()=>{state.items=state.items.filter(i=>i.page!==state.page);state.strokes=state.strokes.filter(i=>i.page!==state.page);state.draft=[];state.selected=null;refreshUI();toast('Page markups cleared')};
function csvCell(v){const s=String(v??'');return/[",\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s}
$('#exportBtn').onclick=()=>{if(!state.items.length)return toast('Nothing to export yet');const rows=[['Item','Group','Type','Page','Segments','Value','Unit','Railing Layout','Stock Sticks','Rail Members'],...state.items.map((i,n)=>{const linear=['length','multilength','joint'].includes(i.type),value=linear?linearValue(i).toFixed(3):i.type==='area'?(state.scale?polyArea(i.points)*state.scale*state.scale:0).toFixed(3):i.type==='angle'?angleValue(i.points).toFixed(2):1,unit=linear?'LF':i.type==='area'?'SF':i.type==='angle'?'DEG':'EA';return[n+1,i.group||'General',i.type,i.page,i.type==='multilength'?i.segments.length:'',value,unit,i.railLayout?.notation||'',i.railCutPlan?.summary?.stockSticks||'',i.railCutPlan?.summary?.railMembers||'']})];const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.file.replace(/\.[^.]+$/,'')||'plan')+'-takeoff.csv';a.click();URL.revokeObjectURL(a.href);toast('Takeoff exported')};
const railingAutomation=window.AtlasRailingAutomation;
const railingModule=tradeRegistry?.get?.('railing');
const layoutProfiles=railingModule?.layoutProfiles||{};
const groupLayoutProfileMap={'862 Type 1 Picket':'862','870 Aluminum Two-Rail':'870','880 Steel Two-Rail':'880','822 Bullet Rail':'822'};

function renderLayoutProfileSelect(){
  const sel=$('#railLayoutProfile');if(!sel)return;
  const current=sel.value;
  sel.innerHTML=Object.values(layoutProfiles).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}${p.automation?.enabled?'':' · reference only'}</option>`).join('');
  if(layoutProfiles[current])sel.value=current;
  else sel.value=groupLayoutProfileMap[state.group]||'actual-two-rail';
}
function syncLayoutProfileFromGroup(force=false){
  const sel=$('#railLayoutProfile');if(!sel)return;
  const mapped=groupLayoutProfileMap[state.group];
  if(mapped&&(force||!sel.value))sel.value=mapped;
  if(mapped&&railProfiles?.some?.(p=>p.id===mapped)&&$('#railProfile'))$('#railProfile').value=mapped;
}
function segmentIntersection(a,b,c,d){
  const r={x:b.x-a.x,y:b.y-a.y},s={x:d.x-c.x,y:d.y-c.y};
  const den=r.x*s.y-r.y*s.x;if(Math.abs(den)<1e-9)return null;
  const q={x:c.x-a.x,y:c.y-a.y};
  const t=(q.x*s.y-q.y*s.x)/den,u=(q.x*r.y-q.y*r.x)/den;
  if(t<-1e-8||t>1+1e-8||u<-1e-8||u>1+1e-8)return null;
  return{x:a.x+t*r.x,y:a.y+t*r.y,t};
}
function expansionStationsFor(it){
  if(it.type!=='length'||!state.scale)return[];
  const run=itemSegments(it),joints=state.items.filter(x=>x.type==='joint'&&x.page===it.page).flatMap(itemSegments);
  const stations=[];let cumulative=0;
  for(const seg of run){
    const segPx=dist(seg[0],seg[1]);
    for(const joint of joints){
      const hit=segmentIntersection(seg[0],seg[1],joint[0],joint[1]);
      if(hit)stations.push((cumulative+segPx*hit.t)*state.scale*12);
    }
    cumulative+=segPx;
  }
  return stations.filter((v,i,a)=>a.findIndex(x=>Math.abs(x-v)<.25)===i).sort((a,b)=>a-b);
}
function renderRailAutoResult(result){
  const box=$('#railAutoResult');if(!box)return;
  const sections=result.sections.map(s=>`<div style="display:flex;justify-content:space-between;gap:8px;border-top:1px solid #2a3442;padding:5px 0"><span>S${s.index}: ${s.bays.map(window.AtlasRailingAutomation.formatInches).join(' • ')}${s.markerAfter?' '+s.markerAfter:''}</span><strong>${window.AtlasRailingAutomation.formatInches(s.overallLength)}″</strong></div>`).join('');
  box.innerHTML=`<strong>${esc(result.profileName)}</strong><div style="font:800 15px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:#e2ac3e;word-break:break-word;margin:6px 0">${esc(result.notation)}</div><div>${window.AtlasRailingAutomation.formatInches(result.totalInches)}″ OAL · ${result.posts} posts · ${result.splices} splice${result.splices===1?'':'s'} · ${result.expansions} expansion joint${result.expansions===1?'':'s'}</div><div style="color:var(--muted);margin:3px 0 7px">Bay range ${window.AtlasRailingAutomation.formatInches(result.minBay)}″–${window.AtlasRailingAutomation.formatInches(result.maxBay)}″ · ${result.valid?'PASS':'CHECK'}</div>${sections}${result.warnings.length?`<div class="warn" style="margin-top:7px">${result.warnings.map(esc).join('<br>')}</div>`:''}`;
  $('#copyRailLayout').hidden=false;
}
$('#autoLayoutRail').onclick=()=>{
  const it=state.items.find(i=>i.id===state.selected);
  if(!it||it.type!=='length')return toast('Select one connected rail length first');
  if(!state.scale)return toast('Calibrate the plan before auto layout');
  const profileId=$('#railLayoutProfile').value;
  try{
    const result=railingAutomation.solve({totalInches:linearValue(it)*12,profileId,expansionStations:expansionStationsFor(it)});
    it.railLayout=result;
    renderRailAutoResult(result);
    renderOverlay();refreshUI();
    toast(result.valid?'Railing layout generated':'Layout generated — check warnings');
  }catch(error){
    $('#railAutoResult').innerHTML=`<span class="warn">${esc(error.message||'Auto layout failed')}</span>`;
    $('#copyRailLayout').hidden=true;
  }
};
$('#copyRailLayout').onclick=async()=>{
  const it=state.items.find(i=>i.id===state.selected);
  if(!it?.railLayout?.notation)return;
  try{await navigator.clipboard.writeText(it.railLayout.notation);toast('Bay layout copied')}catch{toast('Could not copy layout')}
};
window.atlasForgeSolveRailLayout=input=>railingAutomation?.solve?.(input);
const railAutoSelfTest=railingAutomation?.selfTest?.();
if(railAutoSelfTest&&!railAutoSelfTest.pass)console.error('Atlas Forge railing automation self-test failed',railAutoSelfTest);

const defaultRailProfiles=tradeRegistry?.getMaterialProfiles?.('railing')||[{id:'870',name:'870 Aluminum Two-Rail',rails:2,stock:240,post:72,overlap:6,gap:.5,bendPost:21,radius:6,kerf:0,reusableDropMin:0,layoutProfile:'870'},{id:'880',name:'880 Steel Two-Rail',rails:2,stock:240,post:72,overlap:6,gap:.5,bendPost:21,radius:6,kerf:0,reusableDropMin:0,layoutProfile:'880'},{id:'822',name:'822 Bullet Rail',rails:2,stock:240,post:72,overlap:6,gap:.5,bendPost:21,radius:6,kerf:0,reusableDropMin:0,layoutProfile:'822'}];
let railProfiles=[];try{railProfiles=JSON.parse(localStorage.getItem('atlasRailProfiles'))||[]}catch{railProfiles=[]}
for(const standard of defaultRailProfiles){const n=railProfiles.findIndex(p=>p.id===standard.id);if(n>=0)railProfiles[n]={...standard,...railProfiles[n],layoutProfile:railProfiles[n].layoutProfile||standard.layoutProfile};else railProfiles.push({...standard})}
function saveProfiles(){localStorage.setItem('atlasRailProfiles',JSON.stringify(railProfiles));renderProfileSelect()}
function renderProfileSelect(){const sel=$('#railProfile'),current=sel.value;sel.innerHTML=railProfiles.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(railProfiles.some(p=>p.id===current))sel.value=current}
function editProfile(profile){$('#rpName').value=profile?.name||'';$('#rpRails').value=profile?.rails||2;$('#rpStock').value=profile?.stock||240;$('#rpPost').value=profile?.post||72;$('#rpOverlap').value=profile?.overlap||6;$('#rpGap').value=profile?.gap??.5;$('#rpBendPost').value=profile?.bendPost||21;$('#rpRadius').value=profile?.radius||6;$('#rpKerf').value=profile?.kerf??0;$('#rpReusableDrop').value=profile?.reusableDropMin??0;$('#railModal').dataset.id=profile?.id||'';$('#railModal').classList.add('show')}
$('#editRailProfile').onclick=()=>editProfile(railProfiles.find(p=>p.id===$('#railProfile').value));$('#newRailProfile').onclick=()=>editProfile(null);$('#cancelRailProfile').onclick=()=>$('#railModal').classList.remove('show');
$('#saveRailProfile').onclick=()=>{const p={id:$('#railModal').dataset.id||crypto.randomUUID(),name:$('#rpName').value.trim()||'Custom rail system',rails:Math.max(1,Number($('#rpRails').value)||1),stock:Math.max(1,Number($('#rpStock').value)||240),post:Math.max(1,Number($('#rpPost').value)||72),overlap:Math.max(0,Number($('#rpOverlap').value)||0),gap:Math.max(0,Number($('#rpGap').value)||0),bendPost:Math.max(0,Number($('#rpBendPost').value)||21),radius:Math.max(0,Number($('#rpRadius').value)||0),kerf:Math.max(0,Number($('#rpKerf').value)||0),reusableDropMin:Math.max(0,Number($('#rpReusableDrop').value)||0)};const n=railProfiles.findIndex(x=>x.id===p.id);n>=0?railProfiles[n]=p:railProfiles.push(p);saveProfiles();$('#railProfile').value=p.id;$('#railModal').classList.remove('show');toast('Rail profile saved')};

const railingMaterials=window.AtlasRailingMaterials;
function railProfileForLayout(item){
  const selected=railProfiles.find(p=>p.id===$('#railProfile').value);
  if(selected)return selected;
  return railProfiles.find(p=>p.id===item?.railLayout?.profileId)||railProfiles[0];
}
function renderRailCutPlan(plan){
  const box=$('#railCutResult');if(!box)return;
  const fmt=window.AtlasRailingAutomation.formatInches;
  const sticks=plan.sticks.map(stick=>`<div style="border-top:1px solid #2a3442;padding:6px 0"><div style="display:flex;justify-content:space-between;gap:8px"><strong>Stock #${stick.id} · ${fmt(stick.stockLength)}″</strong><span>drop ${fmt(stick.remaining)}″</span></div><div style="color:var(--muted)">${stick.cuts.map(c=>`${esc(c.id)} = ${fmt(c.length)}″`).join(' · ')}</div></div>`).join('');
  const oversize=plan.oversize.map(c=>`<div class="warn">OVERSIZE · ${esc(c.id)} = ${fmt(c.length)}″ exceeds ${fmt(plan.profile.stock)}″ stock by ${fmt(c.overBy)}″</div>`).join('');
  box.innerHTML=`<strong>${esc(plan.profile.name)} cut plan</strong><div style="margin:5px 0">Required rail members: <strong>${plan.summary.railMembers}</strong> · Stock sticks: <strong>${plan.summary.stockSticks}</strong></div><div>Splice sleeves: <strong>${plan.accessories.spliceSleeves}</strong> · Expansion sleeves: <strong>${plan.accessories.expansionSleeves}</strong> · Posts: <strong>${plan.accessories.posts}</strong></div><div style="color:var(--muted);margin:4px 0 7px">Stock ${fmt(plan.profile.stock)}″ · total remaining drop ${fmt(plan.summary.remainingLength)}″ · ${plan.summary.wastePercent}% remaining</div>${sticks}${oversize}${plan.warnings.length?`<div class="warn" style="margin-top:7px">${plan.warnings.map(esc).join('<br>')}</div>`:''}`;
  $('#exportRailCuts').hidden=false;
}
$('#optimizeRailCuts').onclick=()=>{
  const it=state.items.find(i=>i.id===state.selected);
  if(!it?.railLayout)return toast('Auto-layout the selected rail run first');
  const profile=railProfileForLayout(it);
  try{
    const plan=railingMaterials.optimize({layout:it.railLayout,profile});
    it.railMaterialProfileId=profile.id;
    it.railCutPlan=plan;
    renderRailCutPlan(plan);
    refreshUI();
    toast(plan.oversize.length?'Cut list built — stock conflict flagged':'Cut list optimized');
  }catch(error){
    $('#railCutResult').innerHTML=`<span class="warn">${esc(error.message||'Could not build cut list')}</span>`;
    $('#exportRailCuts').hidden=true;
  }
};
function csvText(rows){return rows.map(row=>row.map(csvCell).join(',')).join('\n')}
function downloadText(filename,textContent,type='text/csv'){const blob=new Blob([textContent],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href)}
$('#exportRailCuts').onclick=()=>{
  const it=state.items.find(i=>i.id===state.selected);
  if(!it?.railCutPlan)return toast('Build the cut list first');
  const rows=railingMaterials.toCsv(it.railCutPlan);
  rows.push([]);
  rows.push(['Posts',it.railCutPlan.accessories.posts]);
  rows.push(['Splice Sleeves',it.railCutPlan.accessories.spliceSleeves]);
  rows.push(['Expansion Sleeves',it.railCutPlan.accessories.expansionSleeves]);
  downloadText((state.file.replace(/\.[^.]+$/,'')||'railing')+'-cut-list.csv',csvText(rows));
  toast('Cut list exported');
};
$('#optimizeAllRailCuts').onclick=()=>{
  const entries=state.items.filter(i=>i.railLayout).map((it,n)=>{
    const profile=railProfiles.find(p=>p.id===it.railMaterialProfileId)||railProfiles.find(p=>p.id===it.railLayout.profileId);
    return{name:`Page ${it.page} Run ${n+1}`,layout:it.railLayout,profile};
  });
  if(!entries.length)return toast('No auto-laid-out rail runs found');
  const result=railingMaterials.optimizeMany(entries);
  const groups=result.groups;
  if(!groups.length)return toast('Assign fabrication profiles to the laid-out runs first');
  const fmt=window.AtlasRailingAutomation.formatInches;
  $('#railCutResult').innerHTML=groups.map(g=>`<div style="margin-bottom:10px"><strong>${esc(g.profile.name)} · project nesting</strong><div>${g.runs.length} runs · ${g.summary.railMembers} rail members · ${g.summary.stockSticks} stock sticks</div><div style="color:var(--muted)">Remaining drop ${fmt(g.summary.remainingLength)}″ · ${g.summary.wastePercent}%</div>${g.sticks.map(s=>`<div style="border-top:1px solid #2a3442;padding:4px 0">Stock #${s.id}: ${s.cuts.map(c=>`${esc(c.id)} ${fmt(c.length)}″`).join(' · ')} · drop ${fmt(s.remaining)}″</div>`).join('')}${g.oversize.map(c=>`<div class="warn">OVERSIZE · ${esc(c.id)} = ${fmt(c.length)}″</div>`).join('')}</div>`).join('')+`${result.skipped.length?`<div class="warn">Skipped: ${result.skipped.map(esc).join(', ')}</div>`:''}`;
  $('#exportRailCuts').hidden=true;
  toast('All laid-out runs optimized together');
};
window.atlasForgeOptimizeRailCuts=input=>railingMaterials?.optimize?.(input);
window.atlasForgeOptimizeAllRailCuts=input=>railingMaterials?.optimizeMany?.(input);
const railMaterialSelfTest=railingMaterials?.selfTest?.();
if(railMaterialSelfTest&&!railMaterialSelfTest.pass)console.error('Atlas Forge railing material self-test failed',railMaterialSelfTest);

function crosses(a,b,c,d){const cc=(p1,p2,p3)=>(p3.y-p1.y)*(p2.x-p1.x)>(p2.y-p1.y)*(p3.x-p1.x);return cc(a,c,d)!==cc(b,c,d)&&cc(a,b,c)!==cc(a,b,d)}
function layoutRuleSummary(profile){const layout=tradeRegistry?.getLayoutProfile?.('railing',profile.layoutProfile||profile.id);if(!layout)return'';const sections=Object.entries(layout.sections||{}).map(([key,s])=>s?.pattern?`${key}: ${s.pattern}${Number.isFinite(s.overall)?` = ${s.overall}″ OAL`:''}`:'').filter(Boolean);const max=layout.maxBay? `Max bay ${layout.maxBay}″`:'';const ground=layout.minGroundPostsPerSection? `min ${layout.minGroundPostsPerSection} ground posts/section`:'';return `<br><small><strong>Athena layout rules:</strong> ${[max,ground].filter(Boolean).join(' · ')}${sections.length?`<br>${sections.map(esc).join('<br>')}`:''}</small>`}
$('#calculateRail').onclick=()=>{const it=state.items.find(i=>i.id===state.selected);if(!it||!['length','multilength'].includes(it.type))return toast('Select a length or multi-segment rail run first');if(!state.scale)return toast('Calibrate the plan before calculating railing');const p=railProfiles.find(x=>x.id===$('#railProfile').value)||railProfiles[0],runSegs=it.type==='multilength'?it.segments:itemSegments(it),jointSegs=state.items.filter(x=>x.type==='joint'&&x.page===it.page).flatMap(itemSegments);let crossings=0;for(const a of runSegs)for(const b of jointSegs)if(crosses(a[0],a[1],b[0],b[1]))crossings++;const inches=linearValue(it)*12,corners=it.type==='length'?Math.max(0,it.points.length-2):0,piecesPerRail=Math.max(crossings+1,Math.ceil((inches+crossings*p.overlap)/p.stock)),railPieces=piecesPerRail*p.rails,posts=Math.ceil(inches/p.post)+1,sleeves=crossings*p.rails;$('#railResult').innerHTML=`<strong>${esc(p.name)}</strong><br>${(inches/12).toFixed(2)} LF run · ${railPieces} rail pieces · ${posts} posts<br>${sleeves} expansion sleeves · ${corners} corner bends${crossings?`<br><span class="warn">${crossings} expansion crossing${crossings===1?'':'s'}: solid pieces must break and sleeve.</span>`:''}<br><small>Max post spacing ${p.post}″ · bend-to-post ${p.bendPost}″ max · sleeve gap ${p.gap}″</small>${layoutRuleSummary(p)}`};
function paintPrintMarkup(c,pageNum){c.save();c.lineWidth=3;c.font='bold 14px Arial';c.lineJoin='round';for(const it of state.items.filter(i=>i.page===pageNum)){const color=colors[it.type]||colors.length;c.strokeStyle=color;c.fillStyle=color;c.setLineDash(it.type==='joint'?[10,7]:[]);if(it.type==='count'){c.beginPath();c.arc(it.points[0].x,it.points[0].y,10,0,Math.PI*2);c.fill();c.fillStyle='#111';c.textAlign='center';c.fillText(it.seq,it.points[0].x,it.points[0].y+5);continue}const groups=it.type==='multilength'?it.segments:[it.points];for(const pts of groups){c.beginPath();pts.forEach((p,n)=>n?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));if(it.type==='area')c.closePath();c.stroke()}const p=it.type==='multilength'?it.segments[0][1]:it.type==='angle'?it.points[1]:it.points[Math.floor(it.points.length/2)];c.textAlign='left';c.fillText(formatValue(it),p.x+8,p.y-8);if(it.railLayout?.notation)c.fillText(it.railLayout.notation,p.x+8,p.y+10)}c.setLineDash([]);c.strokeStyle=colors.pen;for(const st of state.strokes.filter(s=>s.page===pageNum)){c.beginPath();st.points.forEach((p,n)=>n?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke()}c.restore()}
async function printablePage(n,markupOnly){const out=document.createElement('canvas'),o=out.getContext('2d');if(state.pdf){const p=await state.pdf.getPage(n),v=p.getViewport({scale:1.5});out.width=Math.round(v.width);out.height=Math.round(v.height);if(markupOnly){o.fillStyle='#fff';o.fillRect(0,0,out.width,out.height)}else await p.render({canvasContext:o,viewport:v}).promise}else{out.width=canvas.width;out.height=canvas.height;if(markupOnly){o.fillStyle='#fff';o.fillRect(0,0,out.width,out.height)}else o.drawImage(canvas,0,0)}paintPrintMarkup(o,n);return out.toDataURL('image/png')}
$('#printBtn').onclick=()=>{if(sheet.hidden)return toast('Open a plan first');$('#printModal').classList.add('show')};$('#cancelPrint').onclick=()=>$('#printModal').classList.remove('show');
$('#startPrint').onclick=async()=>{const w=window.open('','atlas-print');if(!w)return toast('Allow pop-ups to create the print view');$('#printModal').classList.remove('show');w.document.write('<title>Atlas Forge Markups</title><p style="font:16px sans-serif">Preparing marked-up plan…</p>');const scope=$('#printScope').value,nums=scope==='all'?Array.from({length:state.pages},(_,i)=>i+1):[state.page],markupOnly=$('#markupOnly').checked,images=[];for(const n of nums)images.push({n,url:await printablePage(n,markupOnly)});w.document.open();w.document.write(`<title>${esc(state.file)} — Atlas Forge Markups</title><style>@page{margin:.35in}body{margin:0;font-family:Arial}section{break-after:page}section:last-child{break-after:auto}img{width:100%;height:auto}header{font-size:12px;margin:0 0 8px;color:#333}</style>${images.map(x=>`<section><header>Atlas Forge · ${esc(state.file)} · Page ${x.n}</header><img src="${x.url}"></section>`).join('')}<script>addEventListener('load',()=>setTimeout(()=>print(),300))<\/script>`);w.document.close()};
const PROJECT_DB='atlas-forge-projects',PROJECT_STORE='projects';
let projectDbPromise=null,projectHydrating=false,autosaveTimer=null;
function openProjectDb(){if(projectDbPromise)return projectDbPromise;projectDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(PROJECT_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(PROJECT_STORE))request.result.createObjectStore(PROJECT_STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return projectDbPromise}
async function projectStore(mode,work){const db=await openProjectDb();return new Promise((resolve,reject)=>{const tx=db.transaction(PROJECT_STORE,mode),store=tx.objectStore(PROJECT_STORE);let result;try{result=work(store)}catch(error){reject(error);return}tx.oncomplete=()=>resolve(result?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
const projectOwner=()=>window.atlasForgeCurrentUser?.id||'local-user';
function portableDoc(d){return{file:d.file,mime:d.mime||d.source?.type||'',source:d.source,page:d.page,pages:d.pages,zoom:d.zoom,scale:d.scale,items:d.items,strokes:d.strokes,multiId:d.multiId,group:d.group||'General',split:!!d.split,splitPage:d.splitPage||Math.min(2,d.pages)}}
async function saveCurrentProject({silent=false}={}){captureDoc();if(!state.docs.length){if(!silent)toast('Open a plan before saving a project');return}const input=$('#projectName'),name=(input.value||state.projectName||state.file.replace(/\.[^.]+$/,'')||'Untitled project').trim();state.projectId=state.projectId||crypto.randomUUID();state.projectName=name;const record={id:state.projectId,ownerId:projectOwner(),name,updatedAt:new Date().toISOString(),activeDoc:Math.max(0,state.activeDoc),tradePack:state.tradePack,docs:state.docs.map(portableDoc)};await projectStore('readwrite',store=>store.put(record));input.value=name;$('#projectSaveState').textContent='Saved '+new Date(record.updatedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});if(!silent){toast('Project saved on this device');await renderProjectList()}}
function scheduleProjectSave(){if(!state.projectId||projectHydrating)return;clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>saveCurrentProject({silent:true}).catch(()=>{}),900)}
async function allProjects(){const rows=await projectStore('readonly',store=>store.getAll());return(rows||[]).filter(project=>project.ownerId===projectOwner()).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}
async function runtimeDoc(saved){if(!saved.source)throw new Error('The original plan file is missing');const url=URL.createObjectURL(saved.source);let pdf=null,image=null,dxf=null,pages=saved.pages||1;try{if(saved.file.toLowerCase().endsWith('.dxf'))dxf=parseDxf(await saved.source.text());else if(saved.mime==='application/pdf'||saved.file.toLowerCase().endsWith('.pdf')){if(!pdfjs)throw new Error('PDF viewer could not load');pdf=await pdfjs.getDocument(url).promise;pages=pdf.numPages}else image=await loadImage(url);return{...saved,objectUrl:url,pdf,image,dxf,cadPoints:[] ,pages}}catch(error){URL.revokeObjectURL(url);throw error}}
async function openSavedProject(id){const project=await projectStore('readonly',store=>store.get(id));if(!project||project.ownerId!==projectOwner())return toast('Project could not be opened');projectHydrating=true;clearTimeout(autosaveTimer);for(const doc of state.docs)if(doc.objectUrl)URL.revokeObjectURL(doc.objectUrl);const docs=[];try{for(const saved of project.docs)docs.push(await runtimeDoc(saved));state.docs=docs;state.activeDoc=-1;state.projectId=project.id;state.projectName=project.name;state.tradePack=project.tradePack||'railing';$('#projectName').value=project.name;applyTradePack(state.tradePack,true);if(docs.length)await activateDoc(Math.min(project.activeDoc||0,docs.length-1));$('#projectsModal').classList.remove('show');toast('Project opened: '+project.name)}catch(error){toast(error.message||'Project could not be opened')}finally{projectHydrating=false}}
async function deleteSavedProject(id){const projects=await allProjects(),project=projects.find(item=>item.id===id);if(!project||!confirm(`Delete “${project.name}” from this device?`))return;await projectStore('readwrite',store=>store.delete(id));if(state.projectId===id){state.projectId=null;state.projectName=''}await renderProjectList();toast('Saved project deleted')}
async function renderProjectList(){const wrap=$('#projectList'),projects=await allProjects();wrap.innerHTML=projects.length?projects.map(project=>`<div class="project-card"><div><strong>${esc(project.name)}</strong><small>${project.docs.length} plan${project.docs.length===1?'':'s'} · updated ${new Date(project.updatedAt).toLocaleString()}</small></div><div class="control-row"><button class="btn" data-open-project="${project.id}">Open</button><button class="btn" data-delete-project="${project.id}">Delete</button></div></div>`).join(''):'<div class="empty-projects">No saved projects on this device yet.</div>';$$('[data-open-project]').forEach(button=>button.onclick=()=>openSavedProject(button.dataset.openProject));$$('[data-delete-project]').forEach(button=>button.onclick=()=>deleteSavedProject(button.dataset.deleteProject))}
async function showProjects(){const modal=$('#projectsModal');$('#projectName').value=state.projectName||state.file.replace(/\.[^.]+$/,'');$('#projectSaveState').textContent=state.projectId?'Autosave is on for this project.':'';modal.classList.add('show');$('#sidePanel').classList.remove('open');try{await renderProjectList()}catch{toast('Saved projects are unavailable in this browser')}}
$('#projectsBtn').onclick=showProjects;$('#mobileProjectsBtn').onclick=showProjects;$('#closeProjectsBtn').onclick=()=>$('#projectsModal').classList.remove('show');$('#saveProjectBtn').onclick=()=>saveCurrentProject().catch(()=>toast('Project could not be saved'));
const projectObserver=new MutationObserver(scheduleProjectSave);for(const node of [$('#measureList'),$('#scaleText'),$('#docBar')])if(node)projectObserver.observe(node,{childList:true,subtree:true,characterData:true});
renderLayoutProfileSelect();renderProfileSelect();applyTradePack(state.tradePack,true);syncLayoutProfileFromGroup(false);
$('#panelBtn').onclick=()=>$('#sidePanel').classList.toggle('open');
const betaAccessModal=$('#betaAccessModal');
function generateBetaPassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@$';const bytes=crypto.getRandomValues(new Uint8Array(18));return'Forge-'+Array.from(bytes,n=>chars[n%chars.length]).join('')}
function openBetaAccess(){if(!window.atlasForgeIsOwner)return;$('#betaPassword').value=generateBetaPassword();$('#betaAccessStatus').textContent='Copy this password before creating the accounts. It will not be emailed.';$('#betaAccessStatus').classList.remove('error');betaAccessModal.classList.add('show');$('#sidePanel').classList.remove('open')}
$('#betaAccessBtn').onclick=openBetaAccess;$('#mobileBetaAccessBtn').onclick=openBetaAccess;$('#closeBetaAccess').onclick=()=>betaAccessModal.classList.remove('show');$('#generateBetaPassword').onclick=()=>{$('#betaPassword').value=generateBetaPassword();$('#betaAccessStatus').textContent='New temporary password generated.'};
$('#createBetaAccounts').onclick=async()=>{const password=$('#betaPassword').value,button=$('#createBetaAccounts'),status=$('#betaAccessStatus');if(password.length<12){status.textContent='Use at least 12 characters.';status.classList.add('error');return}button.disabled=true;button.textContent='Creating…';status.textContent='';status.classList.remove('error');const result=await window.atlasForgeProvisionBeta?.(password);button.disabled=false;button.textContent='Create four accounts';if(!result||result.error){status.textContent=result?.error||'The accounts could not be created.';status.classList.add('error');return}status.innerHTML=`Four accounts created. Access expires ${new Date(result.expires_at).toLocaleString()}. Keep the password above and share it yourself when ready.`;toast('Four beta accounts created')};
const guideModal=$('#guideModal'),feedbackModal=$('#feedbackModal');
function openGuide(){guideModal.classList.add('show');$('#sidePanel').classList.remove('open')}
function closeGuide(){guideModal.classList.remove('show');const id=window.atlasForgeCurrentUser?.id;if(id)localStorage.setItem('atlasForgeIntroV1:'+id,'seen')}
function openFeedback(type='bug'){feedbackModal.classList.add('show');$('#feedbackType').value=type;$('#feedbackStatus').textContent='';$('#feedbackStatus').classList.remove('error');$('#sidePanel').classList.remove('open');setTimeout(()=>$('#feedbackTitle').focus(),0)}
function closeFeedback(){feedbackModal.classList.remove('show')}
$('#guideBtn').onclick=openGuide;$('#mobileGuideBtn').onclick=openGuide;$('#closeGuideBtn').onclick=closeGuide;
$('#feedbackBtn').onclick=()=>openFeedback('bug');$('#mobileFeedbackBtn').onclick=()=>openFeedback('bug');
$('#guideFeedbackBtn').onclick=()=>{closeGuide();openFeedback('idea')};$('#cancelFeedbackBtn').onclick=closeFeedback;
$('#feedbackForm').addEventListener('submit',async e=>{
  e.preventDefault();
  const button=$('#submitFeedbackBtn'),status=$('#feedbackStatus');
  button.disabled=true;button.textContent='Sending…';status.textContent='';status.classList.remove('error');
  const result=await window.atlasForgeSubmitFeedback?.({feedbackType:$('#feedbackType').value,title:$('#feedbackTitle').value.trim(),details:$('#feedbackDetails').value.trim()});
  button.disabled=false;button.textContent='Send feedback';
  if(!result||result.error){status.textContent=result?.error||'Feedback could not be sent. Please try again.';status.classList.add('error');return}
  status.textContent='Thank you — your feedback was sent.';$('#feedbackForm').reset();
  setTimeout(closeFeedback,1200);
});
function maybeShowIntro(user){if(user?.id&&!localStorage.getItem('atlasForgeIntroV1:'+user.id))openGuide()}
window.addEventListener('atlasforge:ready',e=>maybeShowIntro(e.detail));
if(window.atlasForgeAuthReady)maybeShowIntro(window.atlasForgeCurrentUser);
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});window.addEventListener('appinstalled',()=>{$('#installBtn').hidden=true;installPrompt=null;toast('Atlas Forge installed')});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;return}const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);toast(isiOS?'Tap Share, then Add to Home Screen':'Use your browser menu and choose Install Atlas Forge')};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
for(const el of [$('#stageWrap'),document.body]){el.addEventListener('dragover',e=>{e.preventDefault();$('#dropover').classList.add('show')});el.addEventListener('dragleave',e=>{if(!e.relatedTarget)$('#dropover').classList.remove('show')});el.addEventListener('drop',async e=>{e.preventDefault();$('#dropover').classList.remove('show');for(const file of e.dataTransfer.files)await openFile(file)})}
window.addEventListener('keydown',e=>{if(e.key==='Escape'){state.draft=[];state.selected=null;renderOverlay()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){$('#undoBtn').click()}if((e.key==='Delete'||e.key==='Backspace')&&state.tool==='select'&&state.selected&&!['INPUT','SELECT'].includes(document.activeElement.tagName)){state.items=state.items.filter(i=>i.id!==state.selected);state.selected=null;refreshUI()}if(e.key==='Enter'&&state.tool==='length'&&state.draft.length>=2)finishShape('length');if(e.key==='Enter'&&state.tool==='area'&&state.draft.length>=3)finishShape('area');if(e.key==='Enter'&&state.tool==='joint'&&state.draft.length>=2)finishShape('joint');if(e.key==='Enter'&&state.tool==='multilength'&&state.multiId){state.multiId=null;toast('Multi-segment takeoff complete')}});
refreshUI();
